export const CONTACT = {
  primary: {
    email: 'support@acaciagiving.org',
    noreplyEmail: 'noreply@acaciagiving.org',
    phone: '+1 713 517 3954',
    whatsapp: '+1 713 517 3954',
    whatsappUrl: 'https://wa.me/17135173954',
  },
  offices: [
    {
      country: 'Kenya',
      city: 'Nairobi',
      flag: '🇰🇪',
      address: 'General Waruingi Rd, Nairobi, Kenya',
      locationCode: 'PRCW+3J, Nairobi',
      email: 'kenya@acaciagiving.org',
      mapUrl: 'https://maps.google.com/?q=PRCW%2B3J+Nairobi+Kenya',
      isHQ: true,
    },
    {
      country: 'South Sudan',
      city: 'Wau',
      flag: '🇸🇸',
      address: 'MXVW+CFC, Wau, South Sudan',
      locationCode: 'MXVW+CFC, Wau',
      email: 'southsudan@acaciagiving.org',
      mapUrl: 'https://maps.google.com/?q=MXVW%2BCFC+Wau+South+Sudan',
      isHQ: false,
    },
    {
      country: 'DR Congo',
      city: 'Kinshasa',
      flag: '🇨🇩',
      address: 'J822+692, Kinshasa, Congo - Kinshasa',
      locationCode: 'J822+692, Kinshasa',
      email: 'drcongo@acaciagiving.org',
      mapUrl: 'https://maps.google.com/?q=J822%2B692+Kinshasa+Congo',
      isHQ: false,
    },
    {
      country: 'Morocco',
      city: 'Marrakesh',
      flag: '🇲🇦',
      address: '35 Derb Ihihane, Marrakesh 40000, Morocco',
      locationCode: 'J2Q5+26 Marrakesh',
      email: 'morocco@acaciagiving.org',
      mapUrl: 'https://maps.google.com/?q=J2Q5%2B26+Marrakesh+Morocco',
      isHQ: false,
    },
  ],
  social: {
    facebook: 'https://facebook.com/acaciagiving',
    twitter: 'https://twitter.com/acaciagiving',
    instagram: 'https://instagram.com/acaciagiving',
    linkedin: 'https://linkedin.com/company/acaciagiving',
    youtube: 'https://youtube.com/acaciagiving',
  },
} as const
